### ISSUE TITLE
localised display names

### ISSUE THREAD

**Issue by red031000** [TwitchPlaysPokemon/tpp-core#104]
new core is inconsistent with localised display names, sometimes it pings the localised one, sometimes the non-localised one, wherease the old only pings the non-localised (english) one

1. we need to decide whether we want to ping localised or non-localised
2. we need to make it consistent what it does on response

**Comment by aaaaaa123456789** [comment]
Given that barely anyone is using localized names for actual localization purposes, and that the stream is in English, I'd recommend consistently using the non-localized username, since that's the name most users are far more likely to learn and recognize — making it clear for people _other_ than the pinged user who is being pinged.

**Comment by red031000** [comment]
the idea is that it accepts localised as a user, but it should be consistent with output

**Comment by Felk** [comment]
> the idea is that it accepts localised as a user

see #79 for that
