### ISSUE TITLE
Investigate EventSub whispers

### ISSUE THREAD

**Issue by m4-used-rollout** [TwitchPlaysPokemon/tpp-core#441]
According to community reports, as of October 13, the bot is suddenly no longer reacting to whispers. It is still able to send them. Please investigate whether EventSub changed how whispers work.

**Comment by Felk** [comment]
So far: it appears we're _sometimes_ getting a Bad Request for our EventSub subscription call. TwitchLib only gives us a vague reason and throws the actual reason from twitch away: https://github.com/TwitchLib/TwitchLib.Api/blob/2ea61c70225c0c15d7def7a5808837191e33d778/TwitchLib.Api.Core/HttpCallHandlers/TwitchWebRequest.cs#L124

The EventSub request doesn't get retried because Bad Request currently isn't listed as retryable. Maybe it is?

**Comment by Felk** [comment]
seems to have been fixed by https://github.com/TwitchPlaysPokemon/tpp-core/pull/442

The bad requests' actual message was that a websocket connection cannot have subscriptions of different users.
