### ISSUE TITLE
Implement chat connection (minimal scope)

### ISSUE THREAD

**Issue by Felk** [TwitchPlaysPokemon/tpp-core#8]
A minimal chat service needs to be implemented. The library we intend to use is [TwitchLib](https://github.com/swiftyspiffy/TwitchLib).

The minimal chat service needs to do these things:

- Receive irc messages and pre-process them into their models.
- Save each message to the database (build a log).
- Save the user object to the database, if it didn't exist yet.
- Publish chat and whisper events.
- Process chat join and part events, and publish userlist events
- Potentially support multiple chat providers (e.g. Hitbox, Youtube, etc.)

**Comment by chfoo** [comment]
Progress so far:

> Receive irc messages and pre-process them into their models.

:white_check_mark: Done. 

> Save each message to the database (build a log).

:x: Todo. I think internal discussion decided on PostgreSQL. The schema needs to be designed.

> Save the user object to the database, if it didn't exist yet.

:x: Todo.

> Publish chat and whisper events.

:white_check_mark: Done.

> Process chat join and part events, and publish userlist events

:white_check_mark: Done. Additionally, the entire user list can fetched outside of the pub/sub system.

> Potentially support multiple chat providers (e.g. Hitbox, Youtube, etc.)

:white_check_mark: Done. The service uses a concept of "clients" that are instances of "providers" and requests are routed to the specified client.

**Comment by Felk** [comment]
Postgres supports JSON very nicely: https://www.postgresql.org/docs/10/static/datatype-json.html
Which can come in handy for mapping certain data structures without having to set up crazy amounts of database tables. For example saving polymorphic stuff, like money exchanges, where the origin of a transfer might want to attach various kinds of custom data

**Comment by chfoo** [comment]
So we had an internal discussion that:

* "Save each message to the database (build a log)" shouldn't be done in the database but rather saved to daily log files. Also not in scope of the chat service but in another logging service
* "Save the user object to the database, if it didn't exist yet." is not in scope of the chat service

Additionally, the current implementation stores the provider interfaces and the data models within the chat project. When designing the chat logger, we found main issues:

* It's not possible to have multiple instances of the chat service since it's monolithic.
* The chat logger needs to access the data models in the chat package in order to deserialize them.
* There's no testable client designed to consume and interface with the chat service.
* If the chat service is not monolothic, we need to route requests to an appropriate chat service with the provider

So we need:

* [ ] Chat service configuration to accept multiple instances of chat service
* [ ] Separation of data models and provider interfaces into another project
* [ ] Chat provider library that allows consumption of the chat service (i.e., a library that can deserialize the data models from pub/sub and an Restful client that interacts with the chat service API)
* [ ] A registry service so the chat provider library can route Restful calls to the appropriate chat service running the provider (registering socket ports, HTTP proxying the request, etc) 
* [ ] A chat logger that understands all that above

**Comment by Felk** [comment]
I'm closing this issue because it is very outdated and could be misleading
